### ISSUE TITLE
Non-ASCII character '\xf0'

### ISSUE THREAD

**Issue by msongz** [joelibaceta/video-to-ascii#11]
File "/usr/local/bin/video-to-ascii", line 8
SyntaxError: Non-ASCII character '\xf0' in file /usr/local/bin/video-to-ascii on line 8, but no encoding declared;

**Comment by joelibaceta** [comment]
Hi @msongz thanks for reporting,

The line 8 use an special character to show a 👍 , I going to fix it, ¿Could yo tell me which OS are you using?

```python
8 EPILOG = ("\033[1;37mThanks for trying video-to-ascii!\033[0m 👍")
```

**Comment by msongz** [comment]
@joelibaceta thanks ,  I am using macOS 10.13.6

**Comment by joelibaceta** [comment]
Could you try with the new version (**1.2.0**) ? I remove this char in https://github.com/joelibaceta/video-to-ascii/commit/cd7389caa17a3d4519e2913b28b1c60955445e4e

**Comment by joelibaceta** [comment]
The easy way is uninstall and reinstall again with pip
```
pip uninstall video-to-ascii
pip install video-to-ascii
```
Check the version, sometimes you have to try twice.

**Comment by msongz** [comment]
File "/usr/local/lib/python2.7/site-packages/video_to_ascii/render_strategy/render_strategy.py", line 3, in <module>
    from abc import ABC, abstractmethod
ImportError: cannot import name ABC

**Comment by joelibaceta** [comment]
Are you using python3 ?

**Comment by msongz** [comment]
m@songz ~  python                                                                                                                          ✔  1877  17:50:28
Python 2.7.15 (default, Sep 16 2018, 21:01:16)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by joelibaceta** [comment]
:( Yes that's it, you need python 3

**Comment by msongz** [comment]
m@songzs-iMac  ~  python3                                                                                                                         ✔  1878  17:53:19
Python 3.7.0 (default, Aug 22 2018, 15:22:33)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by joelibaceta** [comment]
Now you should install using pip3 and it should work

**Comment by msongz** [comment]
how could I update, reinstall is still 1.2

**Comment by joelibaceta** [comment]
@msongz Yeah :D
