### ISSUE TITLE
Use entry_points instead of scripts in setup.py

### ISSUE THREAD

**Issue by CallMeTarush** [joelibaceta/video-to-ascii#14]
It'll generate wrappers for Windows as well.

https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation

**Comment by joelibaceta** [comment]
@CallMeTarush thanks for your suggestions, I'm working on it https://github.com/joelibaceta/video-to-ascii/commit/3bd9e5e7ca682d47558e294522d21abbffa0db20

**Comment by joelibaceta** [comment]
Solved in https://github.com/joelibaceta/video-to-ascii/pull/17
