### ISSUE TITLE
I cant install: No module named 'pip._internal'

### ISSUE THREAD

**Issue by hectorprats** [joelibaceta/video-to-ascii#21]
pip3 install video-to-ascii --install-option="--with-audio"
/usr/lib/python3/dist-packages/pip/commands/install.py:212: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting video-to-ascii
  Downloading https://files.pythonhosted.org/packages/69/76/421fff0085dda88307ddb8bf31f4c99de815e707aaca28dae4a44330555f/video_to_ascii-1.2.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wb40_x50/video-to-ascii/setup.py", line 16, in <module>
        install_package('opencv-python')
      File "/tmp/pip-build-wb40_x50/video-to-ascii/setup.py", line 8, in install_package
        from pip._internal import main as pip
    ModuleNotFoundError: No module named 'pip._internal'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wb40_x50/video-to-ascii/

**Comment by secsilm** [comment]
@hectorprats I met the same problem and I solved it by using conda. 

1. Installing anaconda/miniconda first
2. `pip install video-to-ascii`

Hope this helps.
