### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by Alowree** [joelibaceta/video-to-ascii#29]
I've pip installed opencv-python and video-to-ascii in my PC, which runs Windows 10, Chinese simplified version. 
However, I constantly encouter the ValueError when I try to run "video-to-ascii -f filepath" command in terminal. 
Following is a screenshot about my commands. 
![image](https://user-images.githubusercontent.com/57390638/72326656-8a5fc200-36ea-11ea-8115-cb2b68162144.png)
How can I solve this trackback? Thanks.

**Comment by joelibaceta** [comment]
@Alowree thanks for reporting, I'm going to review this

**Comment by joelibaceta** [comment]
@Alowree did you try this in a linux environment?, because currently depends of a tty terminal.

**Comment by joelibaceta** [comment]
Closed, too log time inactive
