### ISSUE TITLE
Doesn't work python 3.8

### ISSUE THREAD

**Issue by MatisseBE** [joelibaceta/video-to-ascii#35]
I got 'AttributeError: module 'time' has no attribute 'clock''. A simple google search let me to believe the 'time.clock()' function has been removed and replace by another.
https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8

**Comment by creativegamer03** [comment]
#30

**Comment by creativegamer03** [comment]
#30

**Comment by joelibaceta** [comment]
Solved in https://github.com/joelibaceta/video-to-ascii/commit/81e34317eed5d5830a801718853ae00a6656e052
