### ISSUE TITLE
time.clock() has been removed in Python3.8

### ISSUE THREAD

**Issue by YigaoFan** [joelibaceta/video-to-ascii#42]
Hi, I run this program to watch some video on macOS. But I encounter problem: AttributeError: module 'time' has no attribute 'clock'.

After I search that, I know: time.clock() has been removed in Python3.8.

I have checked the related line of file, and replace it with time.process_time(). Then it works well. Maybe need to use other API on other OS.
https://github.com/joelibaceta/video-to-ascii/blob/5c812d5e7fd9466050dcdd6d4441ce077f2378d8/video_to_ascii/render_strategy/ascii_strategy.py#L120

**Comment by joelibaceta** [comment]
@YigaoFan thanks for reporting, would you like to do a PR?

**Comment by YigaoFan** [comment]
@joelibaceta OK. I'll PR later.

**Comment by joelibaceta** [comment]
Thanks @YigaoFan

**Comment by YigaoFan** [comment]
#43

**Comment by YigaoFan** [comment]
PR here: #43

**Comment by joelibaceta** [comment]
@YigaoFan the PR was released on 1.2.9
