### ISSUE TITLE
    error: option --with-audio not recognized

### ISSUE THREAD

**Issue by HunterG6700** [joelibaceta/video-to-ascii#53]
D:\>pip3 install video-to-ascii --install-option="--with-audio"
c:\users\footb\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\commands\install.py:230: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Collecting video-to-ascii
  Using cached video_to_ascii-1.2.9.tar.gz (6.1 kB)
Collecting xtermcolor
  Using cached xtermcolor-1.3.tar.gz (3.8 kB)
Collecting ffmpeg-python
  Using cached ffmpeg-python-0.2.0.tar.gz (21 kB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
Skipping wheel build for video-to-ascii, due to binaries being disabled for it.
Skipping wheel build for ffmpeg-python, due to binaries being disabled for it.
Skipping wheel build for future, due to binaries being disabled for it.
Skipping wheel build for xtermcolor, due to binaries being disabled for it.
Installing collected packages: future, xtermcolor, ffmpeg-python, video-to-ascii
    Running setup.py install for future ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\footb\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\footb\\AppData\\Local\\Temp\\pip-install-t_3_1qvw\\future_95a3c7a8272d4d5ebfe5d44600f86280\\setup.py'"'"'; __file__='"'"'C:\\Users\\footb\\AppData\\Local\\Temp\\pip-install-t_3_1qvw\\future_95a3c7a8272d4d5ebfe5d44600f86280\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\footb\AppData\Local\Temp\pip-record-cg0z8f53\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\footb\appdata\local\programs\python\python38\Include\future' --with-audio
         cwd: C:\Users\footb\AppData\Local\Temp\pip-install-t_3_1qvw\future_95a3c7a8272d4d5ebfe5d44600f86280\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --with-audio not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\footb\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\footb\\AppData\\Local\\Temp\\pip-install-t_3_1qvw\\future_95a3c7a8272d4d5ebfe5d44600f86280\\setup.py'"'"'; __file__='"'"'C:\\Users\\footb\\AppData\\Local\\Temp\\pip-install-t_3_1qvw\\future_95a3c7a8272d4d5ebfe5d44600f86280\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\footb\AppData\Local\Temp\pip-record-cg0z8f53\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\footb\appdata\local\programs\python\python38\Include\future' --with-audio Check the logs for full command output.

**Comment by hexxxx** [comment]
same issue on debian 4.19

```
$ pip3 install video-to-ascii --install-option='--with-audio'
/usr/lib/python3/dist-packages/pip/_internal/commands/install.py:222: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting video-to-ascii
  Using cached https://files.pythonhosted.org/packages/5a/f2/2022fcbc812b7eb46ea4fb43e1f67359d05b7719fa4099000ce83e9a85da/video_to_ascii-1.2.9.tar.gz
Collecting ffmpeg-python (from video-to-ascii)
  Using cached https://files.pythonhosted.org/packages/dd/5e/d5f9105d59c1325759d838af4e973695081fbbc97182baf73afc78dec266/ffmpeg-python-0.2.0.tar.gz
Collecting xtermcolor (from video-to-ascii)
  Using cached https://files.pythonhosted.org/packages/65/46/c17b53f040396fb6bc0ee6afd0e809c12580791a61b801728708b48b6711/xtermcolor-1.3.tar.gz
Collecting future (from ffmpeg-python->video-to-ascii)
  Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
Skipping bdist_wheel for video-to-ascii, due to binaries being disabled for it.
Skipping bdist_wheel for ffmpeg-python, due to binaries being disabled for it.
Skipping bdist_wheel for xtermcolor, due to binaries being disabled for it.
Skipping bdist_wheel for future, due to binaries being disabled for it.
Installing collected packages: future, ffmpeg-python, xtermcolor, video-to-ascii
  Running setup.py install for future ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-iw490v_4/future/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-e73bq419/install-record.txt --single-version-externally-managed --compile --with-audio --user --prefix=:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --with-audio not recognized

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-iw490v_4/future/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-e73bq419/install-record.txt --single-version-externally-managed --compile --with-audio --user --prefix=" failed with error code 1 in /tmp/pip-install-iw490v_4/future/
```

**Comment by meiaihara06** [comment]
same here
LinuxMint 20.1

but i found a workaround 
you should install `ffmpeg-python` `xtermcolor` and `future` manually :

`pip3 install future`
`pip3 install xtermcolor`
`pip3 install ffmpeg-python`
and now you can install video-to-ascii without any errors:

`pip3 install video-to-ascii --install-option="--with-audio"`

**Comment by hexxxx** [comment]
Great fix! Thanks so much!
