### ISSUE TITLE
pip install video-to-ascii not installing

### ISSUE THREAD

**Issue by unofficialdxnny** [joelibaceta/video-to-ascii#79]
**Describe the bug**
The pip command throws error and does not install the module
the error is following
```cmd
Collecting video-to-ascii
  Using cached video_to_ascii-1.3.0.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\Users\ahmed\AppData\Local\Temp\pip-install-9apno99s\video-to-ascii_e8b3c15ce1a440489be86a409ed5aee6\setup.py", line 11, in install_package
          main.main(['install', package])
      AttributeError: 'function' object has no attribute 'main'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ahmed\AppData\Local\Temp\pip-install-9apno99s\video-to-ascii_e8b3c15ce1a440489be86a409ed5aee6\setup.py", line 21, in <module>
          install_package('opencv-python')
        File "C:\Users\ahmed\AppData\Local\Temp\pip-install-9apno99s\video-to-ascii_e8b3c15ce1a440489be86a409ed5aee6\setup.py", line 14, in install_package
          __main__._main(['install', package])
      AttributeError: module 'pip.__main__' has no attribute '_main'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
**Desktop (Windows)**
 - OS: Windows 10 
 -  Currently running on Windows-10-10.0.19044-SP0

**Comment by buzz-lightsnack-2007** [comment]
Kindly check out #78 as fixes have already been mentioned there.

**Comment by unofficialdxnny** [comment]
> Kindly check out #78 as fixes have already been mentioned there.

yes ty. For anyone else also on this thread the following will sort it for you 
![image](https://user-images.githubusercontent.com/82535503/167409539-fb549e55-3ae3-4d62-a233-07aac3e668be.png)

**Comment by fwolfst** [comment]
> > Kindly check out #78 as fixes have already been mentioned there.
> 
> yes ty. For anyone else also on this thread the following will sort it for you ![image](https://user-images.githubusercontent.com/82535503/167409539-fb549e55-3ae3-4d62-a233-07aac3e668be.png)

Thanks. The whole command than e.g. looks like `pip3 install -U video-to-ascii==1.2.8` (for anybody not familiar with pips options - like me - , copied from #78).

**Comment by unofficialdxnny** [comment]
> > > Kindly check out #78 as fixes have already been mentioned there.
> > 
> > 
> > yes ty. For anyone else also on this thread the following will sort it for you ![image](https://user-images.githubusercontent.com/82535503/167409539-fb549e55-3ae3-4d62-a233-07aac3e668be.png)
> 
> Thanks. The whole command than e.g. looks like `pip3 install -U video-to-ascii==1.2.8` (for anybody not familiar with pips options - like me - , copied from #78).

This command works perfectly. I am now going to close this question. If anyone seems to get same problem and have tried these solutions feel free to reopen this issue :)

Correct response is `pip3 install -U video-to-ascii==1.2.8`
