### ISSUE TITLE
just a question sorry my english is not that good

### ISSUE THREAD

**Issue by vecnhan** [joelibaceta/video-to-ascii#97]
can you customize the character in ASCII?
Like instead of random char I want to put a specific string like " Welcome" or "Hello" some like that or even emoji

**Comment by joelibaceta** [comment]
Yes, of course! You can customize the characters. In this file https://github.com/joelibaceta/video-to-ascii/blob/master/video_to_ascii/render_strategy/image_processor.py#L6-L9, you’ll find the characters used, but for it to work correctly, it’s important to choose characters whose density goes from greater to lesser, so they can be interpreted as darker colors when contrasted against the black background of the terminal.
